=== hyperflow-wms/hyperflow/schemas/workflow.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://dice.cyfronet.pl/hyperflow",
  "type": "object",
  "properties": {
    "name": {
      "id": "http://dice.cyfronet.pl/hyperflow/name",
      "type": "string"
    },
    "processes": {
      "id": "http://dice.cyfronet.pl/hyperflow/processes",
      "type": "array",
      "items": [
        {
          "id": "http://dice.cyfronet.pl/hyperflow/processes/0",
          "type": "object",
          "properties": {
            "name": {
              "id": "http://dice.cyfronet.pl/hyperflow/processes/0/name",
              "type": "string"
            },
            "type": {
              "id": "http://dice.cyfronet.pl/hyperflow/processes/0/type",
              "type": "string"
            },
            "function": {
              "id": "http://dice.cyfronet.pl/hyperflow/processes/0/function",
              "type": "string"
            },
            "parlevel": {
              "id": "http://dice.cyfronet.pl/hyperflow/processes/0/parlevel",
              "type": "integer"
            },
            "ordering": {
              "id": "http://dice.cyfronet.pl/hyperflow/processes/0/ordering",
              "type": "string"
            },
            "ins": {
              "id": "http://dice.cyfronet.pl/hyperflow/processes/0/ins",
              "type": "array",
              "items": {
                "id": "http://dice.cyfronet.pl/hyperflow/processes/0/ins/0",
                "type": "string"
              }
            },
            "outs": {
              "id": "http://dice.cyfronet.pl/hyperflow/processes/0/outs",
              "type": "array",
              "items": {
                "id": "http://dice.cyfronet.pl/hyperflow/processes/0/outs/0",
                "type": "string"
              }
            }
          }
        }, {
          "id": "http://dice.cyfronet.pl/hyperflow/processes/1",
          "type": "object",
          "properties": {
            "name": {
              "id": "http://dice.cyfronet.pl/hyperflow/processes/1/name",
              "type": "string"
            },
            "type": {
              "id": "http://dice.cyfronet.pl/hyperflow/processes/1/type",
              "type": "string"
            },
            "function": {
              "id": "http://dice.cyfronet.pl/hyperflow/processes/1/function",
              "type": "string"
            },
            "ins": {
              "id": "http://dice.cyfronet.pl/hyperflow/processes/1/ins",
              "type": "array",
              "items": {
                "id": "http://dice.cyfronet.pl/hyperflow/processes/1/ins/0",
                "type": "string"
              }
            },
            "outs": {
              "id": "http://dice.cyfronet.pl/hyperflow/processes/1/outs",
              "type": "array",
              "items": {
                "id": "http://dice.cyfronet.pl/hyperflow/processes/1/outs/0",
                "type": "string"
              }
            }
          }
        }
      ]
    },
    "signals": {
      "id": "http://dice.cyfronet.pl/hyperflow/signals",
      "type": "array",
      "items": [
        {
          "id": "http://dice.cyfronet.pl/hyperflow/signals/0",
          "type": "object",
          "properties": {
            "name": {
              "id": "http://dice.cyfronet.pl/hyperflow/signals/0/name",
              "type": "string"
            },
            "data": {
              "id": "http://dice.cyfronet.pl/hyperflow/signals/0/data",
              "type": "array",
              "items": [
                {
                  "id": "http://dice.cyfronet.pl/hyperflow/signals/0/data/0",
                  "type": "integer"
                }, {
                  "id": "http://dice.cyfronet.pl/hyperflow/signals/0/data/1",
                  "type": "integer"
                }, {
                  "id": "http://dice.cyfronet.pl/hyperflow/signals/0/data/2",
                  "type": "integer"
                }, {
                  "id": "http://dice.cyfronet.pl/hyperflow/signals/0/data/3",
                  "type": "integer"
                }, {
                  "id": "http://dice.cyfronet.pl/hyperflow/signals/0/data/4",
                  "type": "integer"
                }, {
                  "id": "http://dice.cyfronet.pl/hyperflow/signals/0/data/5",
                  "type": "integer"
                }
              ]
            }
          }
        }, {
          "id": "http://dice.cyfronet.pl/hyperflow/signals/1",
          "type": "object",
          "properties": {
            "name": {
              "id": "http://dice.cyfronet.pl/hyperflow/signals/1/name",
              "type": "string"
            }
          }
        }, {
          "id": "http://dice.cyfronet.pl/hyperflow/signals/2",
          "type": "object",
          "properties": {
            "name": {
              "id": "http://dice.cyfronet.pl/hyperflow/signals/2/name",
              "type": "string"
            }
          }
        }
      ]
    },
    "ins": {
      "id": "http://dice.cyfronet.pl/hyperflow/ins",
      "type": "array",
      "items": {
        "id": "http://dice.cyfronet.pl/hyperflow/ins/0",
        "type": "string"
      }
    },
    "outs": {
      "id": "http://dice.cyfronet.pl/hyperflow/outs",
      "type": "array",
      "items": {
        "id": "http://dice.cyfronet.pl/hyperflow/outs/0",
        "type": "string"
      }
    }
  },
  "required": [
    "name",
    "processes",
    "signals",
    "ins",
    "outs"
  ]
}

=== hyperflow-wms/hyperflow/examples/KNative/workflow.json
{
  "name": "knative-example",
  "processes": [
    {
      "name": "knative-example",
      "type": "dataflow",
      "firingLimit": 1,
      "function": "kNativeCommand",
      "config": {
        "image": "tequilac/line-counter",
        "namespace": "exns"
      },
      "ins": [
        "dataUrl"
      ],
      "outs": [
        "results"
      ]
    }
  ],
  "signals": [
    {
      "name": "dataUrl",
      "data": [[
        "http://raw.githubusercontent.com/elastic/examples/master/Common%20Data%20Formats/apache_logs/apache_logs"
      ]]
    }, {
      "name": "results"
    }
  ],
  "ins": [
    "dataUrl"
  ],
  "outs": [
    "results"
  ]
}

=== hyperflow-wms/hyperflow/examples/RemoteJobs/workflow.json
{
  "name": "RemoteJobsTestWorkflow",
  "processes": [ {
    "name": "SubmitRemoteJob",
    "type": "dataflow",
    "parlevel": 0,
    "firingLimit": 1,
    "function": "submitRemoteJob",
    "config": {
      "executor": {
        "executable": "./job.js",
        "args": ["Hello", "world", "number", "number2"],
        "stdout": "RemoteJobTest.stdout",
        "stderr": "RemoteJobTest.error"
      }
    },
    "ins": [ "number", "number2" ],
    "outs": [ ]
  }, {
    "name": "RemoteJobWithPipes",
    "type": "dataflow",
    "firingLimit": 1,
    "function": "submitRemoteJob",
    "config": {
      "executor": {
        "executable": "ls",
        "args": ["-l", "|", "sort", "-r"],
	"shell": true
      }
    },
    "ins": [ "number" ],
    "outs": [ ]
  } ],
  "signals": [ {
    "name": "number",
    "data": [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ],
    "workflow_input": true
  }, {
    "name": "number2",
    "data": [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
  } ],
  "ins": [ "number" ],
  "outs": [ ]
}

=== hyperflow-wms/hyperflow/examples/Sqrsum2/workflow.json
{
    "name": "sumsqr2",
    "processes": [ {
        "name": "Sqr",
	"type": "dataflow",
        "function": "sqr",
        "parlevel": 6,
	"ordering": "true",
        "ins": [ "number" ],
        "outs": [ "square" ]
    }, {
        "name": "Sum",
	"type": "dataflow",
        "function": "sum",
        "executeWhenRecovering": "true",
        "ins": [ "square" ],
        "outs": [ "sum" ]
    } ],
    "signals": [ {
        "name": "number",
        "data": [ 1, 2, 3, 4, 5, 6 ]
    }, {
        "name": "square"
    }, {
        "name": "sum"
    } ],
    "ins": [ "number" ],
    "outs": [ "sum" ]
}

=== hyperflow-wms/hyperflow/examples/Sqrsum/workflow.json
{
    "name": "Wf_SumSquares",
    "processes": [ {
        "name": "Sqr",
	"type": "dataflow",
        "function": "sqr",
        "ins": [ "number" ],
        "outs": [ "square" ]
    }, {
        "name": "Sum",
	"type": "dataflow",
        "function": "sum",
        "ins": [ "square:3" ],
        "outs": [ "sum" ]
    } ],
    "signals": [ {
        "name": "number",
        "data": [ 1, 2, 3, 4, 5, 6 ]
    }, {
        "name": "square"
    }, {
        "name": "sum"
    }  ],
    "ins": [ "number" ],
    "outs": [ "sum" ]
}

=== hyperflow-wms/hyperflow/examples/HashcatKubernetes/workflow.json
{
  "name": "PasswordAudit",
  "processes": [
    {
      "name": "GenerateHashes",
      "type": "dataflow",
      "function": "{{function}}",
      "firingLimit": 1,
      "config": {
        "executor": {
          "executable": "node",
          "args": [
            "./generate.js"
          ]
        }
      },
      "ins": [],
      "outs": [
        "hashes"
      ]
    },
    {
      "name": "FilterHashes",
      "type": "dataflow",
      "firingLimit": 1,
      "function": "{{function}}",
      "config": {
        "executor": {
          "executable": "node",
          "args": [
            "./filter.js"
          ]
        }
      },
      "ins": [
        "hashes"
      ],
      "outs": [
        "filteredHashes"
      ]
    },
    {
      "name": "RunHashcatMD5",
      "type": "dataflow",
      "firingLimit": 1,
      "function": "{{function}}",
      "config": {
        "executor": {
          "executable": "node",
          "args": [
            "./hashcat.js",
            "md5"
          ]
        }
      },
      "ins": [
        "filteredHashes"
      ],
      "outs": [
        "crackedMD5"
      ]
    },
    {
      "name": "RunHashcatSHA1",
      "type": "dataflow",
      "firingLimit": 1,
      "function": "{{function}}",
      "config": {
        "executor": {
          "executable": "node",
          "args": [
            "./hashcat.js",
            "sha1"
          ]
        }
      },
      "ins": [
        "filteredHashes"
      ],
      "outs": [
        "crackedSHA1"
      ]
    },
    {
      "name": "RunHashcatSHA256",
      "type": "dataflow",
      "firingLimit": 1,
      "function": "{{function}}",
      "config": {
        "executor": {
          "executable": "node",
          "args": [
            "./hashcat.js",
            "sha256"
          ]
        }
      },
      "ins": [
        "filteredHashes"
      ],
      "outs": [
        "crackedSHA256"
      ]
    },
    {
      "name": "RunHashcatSHA512",
      "type": "dataflow",
      "firingLimit": 1,
      "function": "{{function}}",
      "config": {
        "executor": {
          "executable": "node",
          "args": [
            "./hashcat.js",
            "sha512"
          ]
        }
      },
      "ins": [
        "filteredHashes"
      ],
      "outs": [
        "crackedSHA512"
      ]
    },
    {
      "name": "SummarizeResults",
      "type": "dataflow",
      "firingLimit": 1,
      "function": "{{function}}",
      "config": {
        "executor": {
          "executable": "node",
          "args": [
            "./summarize.js"
          ]
        }
      },
      "ins": [
        "crackedMD5",
        "crackedSHA1",
        "crackedSHA256",
        "crackedSHA512"
      ],
      "outs": [
        "summary"
      ]
    }
  ],
  "signals": [
    {
      "name": "hashes"
    },
    {
      "name": "filteredHashes"
    },
    {
      "name": "crackedMD5"
    },
    {
      "name": "crackedSHA1"
    },
    {
      "name": "crackedSHA256"
    },
    {
      "name": "crackedSHA512"
    },
    {
      "name": "summary"
    }
  ],
  "ins": [],
  "outs": [
    "summary"
  ]
}

=== hyperflow-wms/hyperflow/examples/BagOfJobs/workflow.json
{
    "name": "BagOfJobsExample",
    "processes": [ {
        "name": "BojExecutor",
	"type": "dataflow",
	"firingLimit": 1,
        "function": "k8sCommand",
	"config": {
		"executor": {
			"image": "hyperflowwms/montage-workflow-worker",
			"executable": "echo",
			"args": ["Hello", "World"]
		}
	},
        "ins": [ "jobSetsFile" ],
        "outs": [ ]
    } ],
    "signals": [ {
        "name": "jobSetsFile",
        "data": [ "job_sets.json" ]
    } ],
    "ins": [ "jobSetsFile" ],
    "outs": [ ]
}
